enum EModals {
  SIGNUP = "SIGNUP",
  SEND_EMAIL = "SEND_EMAIL",
  PASSWORD_UPDATED = "PASSWORD_UPDATED",
  ACCOUNT_VERIFIED = "ACCOUNT_VERIFIED",
  OTP_VERIFIED = "OTP_VERIFIED",
  ACCOUNT_CREATED = "ACCOUNT_CREATED",
  LOGOUT = "LOGOUT",
}

export default EModals;
